name: 'Build and Test'
on:
 pull_request:

jobs:
 build-and-test:
  permissions:
   pull-requests: write
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: 'Install Node'
     uses: actions/setup-node@v4
     with:
      node-version: '20.x'
   - name: 'Install Deps'
     run: npm install
   - name: 'Test'
     run: npm run coverage
   - name: 'Upload Coverage'
     uses: actions/upload-artifact@v4
     with:
      name: coverage-${{ matrix.branch }}
      path: coverage

 report-coverage:
  needs: test
  runs-on: ubuntu-latest
  steps:
   - name: 'Download Coverage Artifacts'
     uses: actions/download-artifact@v4
     with:
      name: coverage-${{ github.head_ref }}
      path: coverage
   - uses: actions/download-artifact@v4
     with:
      name: coverage-main
      path: coverage-main
   - name: 'Report Coverage'
     uses: davelosert/vitest-coverage-report-action@v2
     with:
      json-summary-compare-path: coverage-main/coverage-summary.json
